// Import necessary types and fonts
import type { Metadata } from "next"; // Import Metadata type for defining metadata properties
import { Geist, Geist_Mono } from "next/font/google"; // Import Google fonts from Next.js
import "./globals.css"; // Import global styles
import 'mapbox-gl/dist/mapbox-gl.css'; // Import Mapbox styles to ensure proper rendering

// Define custom fonts with variable names for global usage
const geistSans = Geist({
  variable: "--font-geist-sans", // Define CSS variable for sans-serif font
  subsets: ["latin"], // Specify supported character subsets
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Define CSS variable for monospaced font
  subsets: ["latin"], // Specify supported character subsets
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Page description
};

// Define the RootLayout component, which wraps all pages with global settings
export default function RootLayout({
  children, // Accepts child components
}: Readonly<{
  children: React.ReactNode; // Defines the expected prop type as React nodes
}>) {
  return (
    <html lang="en"> {/* Set language attribute for accessibility and SEO */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Apply custom fonts and antialiasing for smoother text rendering
      >
        {children} {/* Render child components within the layout */}
      </body>
    </html>
  );
}
